In [1]:
import numpy as np

In [15]:
def standart_normal_distr(x): 
    return np.e ** (-x**2 / 2) / np.sqrt(1 * np.pi)

In [16]:
aspirin_total_count = 11037
placebo_total_count = 11034

infarct_aspirin_count = 104
infarct_placebo_count = 189

In [17]:
with_aspirin_sample = [1] * infarct_aspirin_count + [0] * (aspirin_total_count - infarct_aspirin_count)
with_placebo_sample = [1] * infarct_aspirin_count + [0] * (placebo_total_count - infarct_aspirin_count)

In [20]:
infarct_with_aspirin_prob = infarct_aspirin_count / aspirin_total_count
infarct_with_placebo_prob = infarct_placebo_count / placebo_total_count

In [21]:
infarct_with_placebo_prob - infarct_with_aspirin_prob

0.0077060239760047815

In [22]:
from statsmodels.stats.proportion import proportion_confint
from statsmodels.stats.proportion import samplesize_confint_proportion

def get_proportion_confint(sample, method):

    return np.round(proportion_confint(sum(sample), len(sample), 0.05, method), 4)

In [23]:
get_proportion_confint(with_aspirin_sample, 'normal')

array([0.0076, 0.0112])

In [24]:
def get_odds(sample):
    
    return np.sum(p, axis=1) / len(p) / (1 - p)

In [27]:
get_odds(infarct_with_placebo_prob) / get_odds(infarct_with_aspirin_prob)

1.8320539419087138

In [70]:
np.random.seed(0)

def bootstrap_sample_generate(sample, n_samples):
    indices = np.random.randint(0, len(sample), (n_samples, len(sample)))
    data = np.array(sample)[indices]
    
    return data

def stat_intervals(array, alpha):
    boundaries = np.percentile(array, [100 * alpha / 2, 100 * (1 - alpha / 2)])
    return boundaries

In [71]:
stat_intervals(bootstrap_sample_generate(with_aspirin_sample, 1000), 0.05)

array([0., 0.])

In [69]:
bootstrap_sample_generate(with_aspirin_sample, 1000).shape

(1000, 11037)

In [73]:
list(map(get_odds, bootstrap_sample_generate(with_aspirin_sample, 1000)))

<ipython-input-24-43c0aac76330>:2: RuntimeWarning: divide by zero encountered in true_divide
  return p / (1 - p)


[array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 