In [19]:
import pandas as pd
import numpy as np

In [20]:
data = pd.read_csv("water.csv", sep="\t")

In [21]:
data.head()

location        town  mortality  hardness
0    South        Bath       1247       105
1    North  Birkenhead       1668        17
2    South  Birmingham       1466         5
3    North   Blackburn       1800        14
4    North   Blackpool       1609        18

In [25]:
south_towns = data[data['location'] == 'South']
north_towns = data[data['location'] == 'North']

In [26]:
from statsmodels.stats import weightstats

def get_tconfint(sample, param):
    sample_mean = sample[param].mean()
    sample_mean_std = sample[param].std(ddof=1) / np.sqrt(sample.shape[0])

    return np.round(weightstats._tconfint_generic(sample_mean, sample_mean_std, sample.shape[0] - 1, 0.05, 'two-sided'), 4)

In [56]:
get_tconfint(data, 'mortality')

array([1476.0833, 1572.2117])

In [57]:
get_tconfint(south_towns, 'mortality')

array([1320.1517, 1433.4636])

In [58]:
get_tconfint(north_towns, 'mortality')

array([1586.5605, 1680.6395])

In [59]:
get_tconfint(south_towns, 'hardness')

array([53.4672, 86.0713])

In [60]:
get_tconfint(north_towns, 'hardness')

array([21.4225, 39.3775])